"""Command-line entry point for the ToolAhead prototype."""

from __future__ import annotations

import argparse
import json
import os
import shlex
import shutil
import subprocess
import sys
import urllib.request
from pathlib import Path

from .tool_contracts import replayable_command


ROOT = Path(__file__).resolve().parent
CODEX_HOOK = ROOT / "codex_hook.py"
CLAUDE_HOOK = ROOT / "prefetch_hook.py"
REPLAY_HELPER = ROOT / "prefetch_replay.py"
MCP_SERVER = ROOT / "mcp.py"
TOOL_CONTRACTS = ROOT / "tool_contracts.py"
SERVICES = ROOT / "services.py"
ANTIGRAVITY_HOOK = ROOT / "antigravity_hook.py"
ANTIGRAVITY_TOOL_MATCHER = ("run_command|view_file|write_to_file|"
                            "replace_file_content|multi_replace_file_content|"
                            "grep_search|find_by_name")
STATS = ROOT / "prefetch_stats.py"
DEFAULT_URL = "http://127.0.0.1:4242"
MCP_BEGIN = "# >>> ToolAhead managed MCP >>>"
MCP_END = "# <<< ToolAhead managed MCP <<<"
MCP_TOOL_NAMES = [
    "read_file", "search", "list_files", "edit_file", "write_file", "run",
]
CLAUDE_NATIVE_ANALOGS = ["Read", "Grep", "Glob", "Edit", "Write"]
# Prozess-Timeout fuer Hooks, die blockierend auf Service-Readiness warten.
# Muss ueber dem Client-Budget (TOOLAHEAD_ENSURE_WAIT, Default 110s) liegen.
HOOK_ENSURE_TIMEOUT = 120


def _handler(command: str, *, timeout: int = 8) -> dict:
    return {"type": "command", "command": command, "timeout": timeout,
            "statusMessage": "ToolAhead"}


def _group(command: str, *, matcher: str | None = None,
           timeout: int = 8) -> dict:
    value = {"hooks": [_handler(command, timeout=timeout)]}
    if matcher is not None:
        value["matcher"] = matcher
    return value


def _merge_codex_hooks(config: dict, command: str) -> dict:
    hooks = config.setdefault("hooks", {})
    wanted = {
        "SessionStart": _group(command),
        "UserPromptSubmit": _group(command),
        # PreToolUse traegt die blockierende Service-Readiness-Wartezeit. Das
        # Prozess-Timeout muss deshalb ueber dem Ensure-Budget liegen, sonst
        # killt Codex den Hook mitten im Warten und der Call laeuft doch zu
        # frueh — die Garantie waere nur behauptet.
        "PreToolUse": _group(
            command, matcher="Bash|apply_patch", timeout=HOOK_ENSURE_TIMEOUT),
        "PostToolUse": _group(
            command, matcher="Bash|apply_patch", timeout=90),
        "Stop": _group(command),
        # Codex clamps SessionEnd hooks to at most three seconds.
        "SessionEnd": _group(command, timeout=3),
    }
    for event, group in wanted.items():
        existing = hooks.setdefault(event, [])
        # Replace only groups previously generated by ToolAhead. This updates
        # copied hook paths without touching unrelated project hooks.
        existing[:] = [
            item for item in existing
            if not (isinstance(item, dict) and any(
                isinstance(hook, dict) and hook.get("statusMessage") == "ToolAhead"
                for hook in item.get("hooks", [])))
        ]
        existing.append(group)
    return config


def _runtime(project: Path) -> tuple[Path, Path]:
    runtime = project / ".toolahead" / "runtime"
    return runtime, runtime / "toolahead_mcp.py"


def _install_mcp_runtime(project: Path) -> Path:
    runtime, installed_mcp = _runtime(project)
    runtime.mkdir(parents=True, exist_ok=True)
    shutil.copy2(MCP_SERVER, installed_mcp)
    shutil.copy2(TOOL_CONTRACTS, runtime / "tool_contracts.py")
    shutil.copy2(SERVICES, runtime / "services.py")
    return installed_mcp


def _codex_mcp_block(project: Path, installed_mcp: Path, url: str) -> str:
    values = {
        "command": "python3",
        "args": [str(installed_mcp), "--workspace", str(project),
                 "--url", url],
    }
    args = ", ".join(json.dumps(item) for item in values["args"])
    return "\n".join([
        MCP_BEGIN,
        "[mcp_servers.toolahead]",
        f"command = {json.dumps(values['command'])}",
        f"args = [{args}]",
        "startup_timeout_sec = 10.0",
        "tool_timeout_sec = 130.0",
        "enabled_tools = [" + ", ".join(json.dumps(name)
                                         for name in MCP_TOOL_NAMES) + "]",
        'env = { TOOLAHEAD_MCP_EVENTS = "1" }',
        MCP_END,
    ])


def _merge_managed_toml(existing: str, block: str) -> str:
    if MCP_BEGIN in existing or MCP_END in existing:
        if MCP_BEGIN not in existing or MCP_END not in existing:
            raise ValueError("incomplete ToolAhead managed block")
        start = existing.index(MCP_BEGIN)
        end = existing.index(MCP_END, start) + len(MCP_END)
        merged = existing[:start].rstrip() + "\n\n" + block + existing[end:]
    else:
        if "[mcp_servers.toolahead]" in existing:
            raise ValueError(
                "existing unmanaged [mcp_servers.toolahead] section; remove or rename it")
        merged = existing.rstrip() + ("\n\n" if existing.strip() else "") + block
    return merged.rstrip() + "\n"


def _replay_enabled(args) -> bool:
    """MCP-Tool-Ersatz ist Opt-in; --strict impliziert ihn."""
    return bool(getattr(args, "replay_tools", False)
                or getattr(args, "strict", False))


def _remove_managed_toml(existing: str) -> str:
    """Entfernt jeden verwalteten Block — und nur den.

    Fehlt die Endmarke, wird NICHT bis zum Dateiende geloescht: dahinter
    stehen womoeglich eigene Sektionen des Nutzers. Der Aktivierungspfad
    verweigert denselben Fall bereits; hier gilt dasselbe.
    """
    while MCP_BEGIN in existing:
        start = existing.index(MCP_BEGIN)
        if MCP_END not in existing[start:]:
            raise ValueError(
                "incomplete ToolAhead managed block: end marker missing; "
                "remove the block by hand to avoid deleting your own config")
        end = existing.index(MCP_END, start) + len(MCP_END)
        existing = existing[:start].rstrip() + "\n" + existing[end:].lstrip()
    return existing.strip() + "\n" if existing.strip() else ""


def _merge_claude_hook(config: dict, command: str) -> dict:
    """Registriert den ToolAhead-Hook fuer Events und raeumt alte Eintraege.

    PreToolUse Bash traegt Ensure-Wartezeit fuer deklarierte Services und
    Replay — deshalb das grosse Timeout. PostToolUse liefert das
    authoritative Lern- und Mutations-Signal fuer native Tools, damit
    Pre-Warming auch ohne die ToolAhead-MCP-Tools funktioniert.
    """
    hooks = config.setdefault("hooks", {})
    wanted = {
        "PreToolUse": _group(command, matcher="Bash",
                             timeout=HOOK_ENSURE_TIMEOUT),
        "PostToolUse": _group(
            command, matcher="Bash|Edit|Write|MultiEdit|NotebookEdit|"
                             "Read|Grep|Glob", timeout=10),
        "UserPromptSubmit": _group(command, timeout=5),
        "Stop": _group(command, timeout=5),
    }
    for event, group in wanted.items():
        existing = hooks.setdefault(event, [])
        existing[:] = [
            item for item in existing
            if not (isinstance(item, dict) and any(
                isinstance(hook, dict)
                and hook.get("statusMessage") == "ToolAhead"
                for hook in item.get("hooks", [])))
        ]
        existing.append(group)
    return config


def _owned_denies_path(project: Path) -> Path:
    """Wo notiert ist, welche Deny-Eintraege ToolAhead selbst gesetzt hat."""
    return project / ".toolahead" / "claude-denies.json"


def _read_owned_denies(project: Path) -> list[str]:
    try:
        value = json.loads(_owned_denies_path(project).read_text(
            encoding="utf-8"))
    except (OSError, ValueError):
        return []
    return [item for item in value if isinstance(item, str)] \
        if isinstance(value, list) else []


def _write_owned_denies(project: Path, names: list[str]) -> None:
    path = _owned_denies_path(project)
    if names:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(sorted(names), indent=2) + "\n",
                        encoding="utf-8")
    elif path.exists():
        path.unlink()


def _enable_claude_strict_routing(config: dict, project: Path | None = None) -> dict:
    """Hide native analogs so the model sees one coherent file-tool suite.

    Merkt sich, welche Eintraege ToolAhead wirklich HINZUGEFUEGT hat. Nur die
    duerfen spaeter wieder verschwinden — eine schon vorher vorhandene
    Deny-Regel gehoert dem Nutzer.
    """
    permissions = config.setdefault("permissions", {})
    if not isinstance(permissions, dict):
        raise ValueError("'permissions' must be an object")
    deny = permissions.setdefault("deny", [])
    if not isinstance(deny, list):
        raise ValueError("'permissions.deny' must be an array")
    added = []
    for name in CLAUDE_NATIVE_ANALOGS:
        if name not in deny:
            deny.append(name)
            added.append(name)
    if project is not None:
        # Frueher Hinzugefuegtes bleibt vermerkt: ein zweiter --strict-Lauf
        # fuegt nichts mehr hinzu, der Besitz von damals gilt weiter.
        _write_owned_denies(project,
                            sorted(set(added) | set(_read_owned_denies(project))))
    return config


def _disable_claude_strict_routing(config: dict, project: Path | None = None) -> dict:
    """Restore the native file tools when strict routing is not requested.

    Without this, a later non-strict init removes the ToolAhead MCP tools but
    leaves the denials in place — the agent would then have neither the native
    nor the replacement file tools.

    Entfernt werden ausschliesslich Eintraege, die ToolAhead nachweislich
    selbst gesetzt hat. Ein Projekt, das ``Edit``/``Write`` aus eigenen
    Gruenden sperrt, behaelt seine Regeln — die haben wir nie angefasst.
    """
    owned = set(_read_owned_denies(project)) if project is not None else set()
    if not owned:
        return config
    permissions = config.get("permissions")
    if not isinstance(permissions, dict):
        _write_owned_denies(project, [])
        return config
    deny = permissions.get("deny")
    if not isinstance(deny, list):
        _write_owned_denies(project, [])
        return config
    permissions["deny"] = [name for name in deny if name not in owned]
    if not permissions["deny"]:
        permissions.pop("deny")
    if not permissions:
        config.pop("permissions", None)
    _write_owned_denies(project, [])
    return config


def _strict_marker(project: Path) -> Path:
    return project / ".toolahead" / "strict-mcp"


def init_codex(args) -> int:
    project = Path(args.project).resolve()
    path = project / ".codex" / "hooks.json"
    mcp_config = project / ".codex" / "config.toml"
    hook_dir = project / ".codex" / "hooks" / "toolahead"
    installed_hook = hook_dir / "codex_hook.py"
    _runtime_dir, installed_mcp = _runtime(project)
    url = getattr(args, "url", DEFAULT_URL)
    # Die Daemon-Adresse gehoert in den Hook-Command: sonst fragt jedes
    # Projekt den Default-Port und damit womoeglich einen fremden Daemon.
    command = shlex.join(["python3", str(installed_hook), "--url", url])
    if path.exists():
        try:
            config = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            print(f"Cannot merge invalid {path}: {exc}", file=sys.stderr)
            return 2
        if not isinstance(config, dict):
            print(f"Cannot merge non-object {path}", file=sys.stderr)
            return 2
    else:
        config = {"description": "ToolAhead Codex lifecycle integration."}
    merged = _merge_codex_hooks(config, command)
    payload = json.dumps(merged, indent=2, ensure_ascii=False) + "\n"
    replay_tools = _replay_enabled(args)
    try:
        existing_toml = mcp_config.read_text(encoding="utf-8") \
            if mcp_config.exists() else ""
        if replay_tools:
            mcp_payload = _merge_managed_toml(
                existing_toml, _codex_mcp_block(project, installed_mcp, url))
        else:
            mcp_payload = _remove_managed_toml(existing_toml)
    except (OSError, ValueError) as exc:
        print(f"Cannot merge {mcp_config}: {exc}", file=sys.stderr)
        return 2
    if args.dry_run:
        print(f"# {path}\n{payload}# {mcp_config}\n{mcp_payload}", end="")
        return 0
    hook_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(CODEX_HOOK, installed_hook)
    shutil.copy2(REPLAY_HELPER, hook_dir / "prefetch_replay.py")
    _install_mcp_runtime(project)
    marker = _strict_marker(project)
    if getattr(args, "strict", False):
        marker.parent.mkdir(parents=True, exist_ok=True)
        marker.write_text("strict MCP routing enabled\n", encoding="utf-8")
    elif marker.exists():
        # Ohne --strict darf kein Marker ueberleben: der Hook wuerde sonst
        # weiter auf MCP-Tools verweisen, die dieser Lauf gerade entfernt.
        marker.unlink()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(payload, encoding="utf-8")
    if mcp_payload or mcp_config.exists():
        mcp_config.write_text(mcp_payload, encoding="utf-8")
    replay = project / ".prefetch-replay.json"
    if not replay.exists():
        replay.write_text('{\n  "commands": []\n}\n', encoding="utf-8")
    print(f"Installed Codex hooks: {path}")
    if replay_tools:
        print(f"Installed Codex MCP:   {mcp_config}")
    else:
        print("MCP replay tools:      off (hooks-only; add --replay-tools "
              "for Read/Search replay)")
    print(f"Hook runtime:          {hook_dir}")
    print(f"Replay allowlist:       {replay}")
    if getattr(args, "strict", False):
        print("Routing:                strict (ToolAhead file tools preferred)")
    print("Open /hooks in Codex once to review and trust the hook definition.")
    return 0


def init_claude(args) -> int:
    project = Path(args.project).resolve()
    settings_path = project / ".claude" / "settings.json"
    mcp_path = project / ".mcp.json"
    runtime, installed_mcp = _runtime(project)
    installed_hook = runtime / "prefetch_hook.py"
    url = getattr(args, "url", DEFAULT_URL)
    hook_command = shlex.join(["python3", str(installed_hook), "--url", url])

    def load_object(path: Path) -> dict:
        if not path.exists():
            return {}
        value = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(value, dict):
            raise ValueError("top-level JSON value must be an object")
        return value

    replay_tools = _replay_enabled(args)
    try:
        settings = _merge_claude_hook(load_object(settings_path), hook_command)
        # Strict-Routing spiegelt IMMER das aktuelle Flag: sonst bleiben nach
        # einem frueheren --strict die Deny-Eintraege stehen, waehrend dieser
        # Lauf die MCP-Ersatz-Tools entfernt.
        settings = _enable_claude_strict_routing(settings, project) \
            if getattr(args, "strict", False) \
            else _disable_claude_strict_routing(settings, project)
        mcp = load_object(mcp_path)
    except (OSError, ValueError) as exc:
        print(f"Cannot merge Claude project config: {exc}", file=sys.stderr)
        return 2
    servers = mcp.setdefault("mcpServers", {})
    if not isinstance(servers, dict):
        print(f"'mcpServers' must be an object in {mcp_path}", file=sys.stderr)
        return 2
    if replay_tools:
        servers["toolahead"] = {
            "type": "stdio",
            "command": "python3",
            "args": [str(installed_mcp), "--workspace", str(project),
                     "--url", url],
            # The MCP server observes the actual tool completion, unlike the
            # SSE stream which only contains the model's requested tool call.
            # Keep lifecycle events enabled so successful Edit/Write calls can
            # advance latest-mutation-wins generations authoritatively.
            "env": {"TOOLAHEAD_MCP_EVENTS": "1"},
        }
    else:
        servers.pop("toolahead", None)
    settings_payload = json.dumps(settings, indent=2, ensure_ascii=False) + "\n"
    mcp_payload = json.dumps(mcp, indent=2, ensure_ascii=False) + "\n"
    if args.dry_run:
        print(f"# {settings_path}\n{settings_payload}# {mcp_path}\n{mcp_payload}",
              end="")
        return 0
    _install_mcp_runtime(project)
    shutil.copy2(CLAUDE_HOOK, installed_hook)
    shutil.copy2(REPLAY_HELPER, runtime / "prefetch_replay.py")
    settings_path.parent.mkdir(parents=True, exist_ok=True)
    settings_path.write_text(settings_payload, encoding="utf-8")
    if servers or mcp_path.exists():
        mcp_path.write_text(mcp_payload, encoding="utf-8")
    replay = project / ".prefetch-replay.json"
    if not replay.exists():
        replay.write_text('{\n  "commands": []\n}\n', encoding="utf-8")
    print(f"Installed Claude hooks: {settings_path}")
    if replay_tools:
        print(f"Installed Claude MCP:   {mcp_path}")
    else:
        print("MCP replay tools:       off (hooks-only; add --replay-tools "
              "for Read/Search replay)")
    print(f"Replay allowlist:       {replay}")
    if getattr(args, "strict", False):
        print("Routing:                strict (native Read/Grep/Glob/Edit/Write hidden)")
    return 0


def init_antigravity(args) -> int:
    """Workspace-local MCP config for Google Antigravity (CLI and IDE).

    Antigravity discovers stdio servers from ``.agents/mcp_config.json`` in
    the active project. There is no ToolAhead lifecycle hook here yet: the
    MCP server's own PreToolUse/PostToolUse reports are the only event
    source, which already drives learning and latest-mutation-wins for every
    call routed through the ToolAhead tools.
    """
    project = Path(args.project).resolve()
    mcp_path = project / ".agents" / "mcp_config.json"
    runtime, installed_mcp = _runtime(project)
    url = getattr(args, "url", DEFAULT_URL)

    def load_object(path: Path) -> dict:
        if not path.exists():
            return {}
        value = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(value, dict):
            raise ValueError("top-level JSON value must be an object")
        return value

    replay_tools = _replay_enabled(args)
    try:
        mcp = load_object(mcp_path)
    except (OSError, ValueError) as exc:
        print(f"Cannot merge Antigravity workspace config: {exc}",
              file=sys.stderr)
        return 2
    servers = mcp.setdefault("mcpServers", {})
    if not isinstance(servers, dict):
        print(f"'mcpServers' must be an object in {mcp_path}", file=sys.stderr)
        return 2
    if replay_tools:
        servers["toolahead"] = {
            "command": "python3",
            "args": [str(installed_mcp), "--workspace", str(project),
                     "--url", url],
            "env": {"TOOLAHEAD_MCP_EVENTS": "1"},
        }
    else:
        servers.pop("toolahead", None)
    hooks_path = project / ".agents" / "hooks.json"
    installed_hook = runtime / "antigravity_hook.py"

    def _hook_handler(event: str, timeout: int = 5) -> dict:
        command = shlex.join(["python3", str(installed_hook), event,
                              "--url", url])
        return {"type": "command", "command": command, "timeout": timeout}

    def _hook_group(event: str, matcher: str, timeout: int = 5) -> list:
        return [{"matcher": matcher,
                 "hooks": [_hook_handler(event, timeout)]}]

    def _flat_hooks(event: str, timeout: int = 5) -> list:
        """Stop kennt keine Matcher-Gruppen, sondern eine flache Handler-Liste."""
        return [_hook_handler(event, timeout)]

    try:
        hooks = load_object(hooks_path)
    except (OSError, ValueError) as exc:
        print(f"Cannot merge Antigravity hooks config: {exc}",
              file=sys.stderr)
        return 2
    hooks["toolahead"] = {
        # PreToolUse wartet bei deklarierten Kommandos blockierend auf
        # Service-Readiness — deshalb das grosse Timeout.
        "PreToolUse": _hook_group("PreToolUse", ANTIGRAVITY_TOOL_MATCHER,
                                  timeout=HOOK_ENSURE_TIMEOUT),
        "PostToolUse": _hook_group("PostToolUse", ANTIGRAVITY_TOOL_MATCHER),
        "Stop": _flat_hooks("Stop"),
    }
    mcp_payload = json.dumps(mcp, indent=2, ensure_ascii=False) + "\n"
    hooks_payload = json.dumps(hooks, indent=2, ensure_ascii=False) + "\n"
    if args.dry_run:
        print(f"# {mcp_path}\n{mcp_payload}# {hooks_path}\n{hooks_payload}",
              end="")
        return 0
    _install_mcp_runtime(project)
    shutil.copy2(ANTIGRAVITY_HOOK, installed_hook)
    mcp_path.parent.mkdir(parents=True, exist_ok=True)
    if servers or mcp_path.exists():
        mcp_path.write_text(mcp_payload, encoding="utf-8")
    hooks_path.write_text(hooks_payload, encoding="utf-8")
    replay = project / ".prefetch-replay.json"
    if not replay.exists():
        replay.write_text('{\n  "commands": []\n}\n', encoding="utf-8")
    print(f"Installed Antigravity hooks: {hooks_path}")
    if replay_tools:
        print(f"Installed Antigravity MCP:   {mcp_path}")
        print("Run /mcp once in the prompt panel to confirm toolahead is "
              "enabled.")
    else:
        print("MCP replay tools:            off (hooks-only; add "
              "--replay-tools for Read/Search replay)")
    print(f"Runtime:                     {installed_mcp.parent}")
    print(f"Replay allowlist:            {replay}")
    return 0


INIT_AGENTS = {"codex": init_codex, "claude": init_claude,
               "antigravity": init_antigravity}


def init_all(args) -> int:
    if args.agent == "both":
        agents = ("codex", "claude")
    elif args.agent == "all":
        agents = ("codex", "claude", "antigravity")
    else:
        agents = (args.agent,)
    for agent in agents:
        result = INIT_AGENTS[agent](args)
        if result:
            return result
    return 0


def allow_command(args) -> int:
    if not replayable_command(args.command):
        print("Only a single deterministic test/build/lint command can be replayed; "
              "shell chains, substitutions, installers, and arbitrary commands are rejected.",
              file=sys.stderr)
        return 2
    project = Path(args.project).resolve()
    path = project / ".prefetch-replay.json"
    data = {"commands": []}
    if path.exists():
        try:
            loaded = json.loads(path.read_text(encoding="utf-8"))
            if isinstance(loaded, dict):
                data = loaded
        except (OSError, ValueError) as exc:
            print(f"Cannot update invalid {path}: {exc}", file=sys.stderr)
            return 2
    commands = data.setdefault("commands", [])
    if not isinstance(commands, list):
        print(f"'commands' must be a list in {path}", file=sys.stderr)
        return 2
    if args.command not in commands:
        commands.append(args.command)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n",
                    encoding="utf-8")
    print(f"Allowed exact replay command in {path}:\n  {args.command}")
    return 0


def trust(args) -> int:
    from .services import ServiceManager, config_digest, trust_workspace

    project = Path(args.project).resolve()
    if config_digest(str(project)) is None:
        print(f"No toolahead.toml found in {project}", file=sys.stderr)
        return 2
    warnings: list[str] = []
    manager = ServiceManager.load(
        str(project),
        on_event=lambda kind, msg: warnings.append(msg)
        if kind == "warn" and "ignoriert" in msg else None)
    print(f"toolahead.toml in {project} declares:")
    for name, spec in manager.specs.items():
        check = spec.ready.kind if spec.ready else "process"
        print(f"  service  {name:20} prewarm={spec.prewarm:8} ready={check}")
        print(f"           $ {spec.command}")
        if spec.warm_routes:
            # Warm-Routen sind automatische HTTP-GETs gegen den Service.
            # Wer freigibt, muss sehen, was spaeter ungefragt abgerufen wird.
            targets = ", ".join(spec.warm_routes)
            print(f"           auto-GET {spec.base_url() or '?'} → {targets}")
    for rule in manager.rules:
        print(f"  command  {rule.match!r} requires {list(rule.requires)} "
              "(never replayed/cached)")
    for message in warnings:
        print(f"  ⚠ {message}")
    if not manager.specs and not manager.rules:
        print("  (no valid services or commands)")
    digest = trust_workspace(str(project))
    print(f"\nTrusted this exact config (sha256 {digest[:16]}…). Service "
          "commands above will run unsandboxed in this workspace. Any change "
          "to toolahead.toml revokes this automatically — rerun "
          "`toolahead trust` after editing it.")
    return 0


def serve(args) -> int:
    from . import proxy

    httpd, upstream_proxy, engine = proxy.build(
        port=args.port, upstream=args.upstream, workspace=args.workspace,
        table=args.table)
    port = httpd.server_address[1]
    print(f"ToolAhead listening on http://127.0.0.1:{port}")
    print(f"Workspace: {engine.workspace}")
    print(f"Anthropic upstream: {upstream_proxy.scheme}://"
          f"{upstream_proxy.host}:{upstream_proxy.port}")
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        return 0
    finally:
        engine.shutdown()
        httpd.server_close()
    return 0


def mcp_serve(args) -> int:
    from .mcp import ToolAheadMCP, serve_stdio

    server = ToolAheadMCP(
        args.workspace, args.url, lookup_wait=args.lookup_wait,
        replay_wait=args.replay_wait, command_timeout=args.command_timeout,
        report_events=not args.no_events)
    return serve_stdio(server)


def status(args) -> int:
    command = [sys.executable, str(STATS), "--url", args.url]
    if args.json:
        command.append("--json")
    return subprocess.call(command)


def codex_exec(args) -> int:
    from .codex_events import AsyncSender, DEFAULT_URL, relay

    codex_args = args.codex_args[1:] if args.codex_args[:1] == ["--"] else args.codex_args
    command = ["codex", "exec", "--json", *codex_args]
    sender = AsyncSender(args.event_url or DEFAULT_URL, args.event_timeout)
    try:
        process = subprocess.Popen(command, stdout=subprocess.PIPE, text=True,
                                   bufsize=1)
        assert process.stdout is not None
        relay(process.stdout, sender, sys.stdout)
        return int(process.wait())
    finally:
        sender.close()


def doctor(args) -> int:
    project = Path(args.project).resolve()
    checks = []
    checks.append(("Python >= 3.11", sys.version_info >= (3, 11), sys.version.split()[0]))
    codex = shutil.which("codex")
    checks.append(("Codex CLI", bool(codex), codex or "not found"))
    hooks = project / ".codex" / "hooks.json"
    checks.append(("Codex hooks", hooks.exists(), str(hooks)))
    codex_mcp = project / ".codex" / "config.toml"
    codex_mcp_ok = codex_mcp.exists() and "[mcp_servers.toolahead]" in \
        codex_mcp.read_text(encoding="utf-8", errors="replace")
    claude_mcp = project / ".mcp.json"
    claude_ok = False
    try:
        claude_data = json.loads(claude_mcp.read_text(encoding="utf-8"))
        claude_ok = isinstance(claude_data.get("mcpServers", {}).get("toolahead"), dict)
    except (OSError, ValueError, AttributeError):
        pass
    # Die MCP-Replay-Tools sind seit 0.6 optional. Sie zu fordern wuerde eine
    # korrekte Default-Installation als kaputt melden. Geprueft wird deshalb
    # nur Konsistenz: wer strict eingerichtet hat, braucht sie auch.
    strict = _strict_marker(project).exists()
    if strict or codex_mcp_ok or claude_ok:
        if strict or codex_mcp_ok:
            checks.append(("Codex MCP", codex_mcp_ok, str(codex_mcp)))
        if strict or claude_ok:
            checks.append(("Claude MCP", claude_ok, str(claude_mcp)))
    else:
        checks.append(("MCP replay tools", True,
                       "off (hooks-only; add --replay-tools to enable)"))
    replay = project / ".prefetch-replay.json"
    checks.append(("Replay allowlist", replay.exists(), str(replay)))
    try:
        with urllib.request.urlopen(args.url.rstrip("/") + "/__prefetch/stats",
                                    timeout=1) as response:
            daemon = response.status == 200
    except Exception:
        daemon = False
    checks.append(("Local daemon", daemon, args.url))
    for label, ok, detail in checks:
        print(f"{'✓' if ok else '✗'} {label:18} {detail}")
    return 0 if all(ok for _label, ok, _detail in checks) else 1


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="toolahead")
    # Bewusst nicht required: `toolahead` ohne Argumente ist das Erste, was
    # jemand tippt. Eine Fehlermeldung als Begruessung waere die schlechteste
    # denkbare erste Sekunde mit dem Werkzeug.
    sub = parser.add_subparsers(dest="subcommand")

    serve_cmd = sub.add_parser("serve", help="start the local daemon/proxy")
    serve_cmd.add_argument("--workspace", default=os.getcwd())
    serve_cmd.add_argument("--port", type=int, default=4242)
    serve_cmd.add_argument("--upstream", default="https://api.anthropic.com")
    serve_cmd.add_argument("--table")
    serve_cmd.set_defaults(func=serve)

    init_cmd = sub.add_parser("init-codex", help="install project-local Codex hooks")
    init_cmd.add_argument("--project", default=os.getcwd())
    init_cmd.add_argument("--url", default=DEFAULT_URL)
    init_cmd.add_argument("--dry-run", action="store_true")
    init_cmd.add_argument("--replay-tools", action="store_true",
                          help="also register the ToolAhead MCP tools for "
                               "Read/Search replay hits")
    init_cmd.add_argument("--strict", action="store_true",
                          help="route file tools through ToolAhead MCP "
                               "(implies --replay-tools)")
    init_cmd.set_defaults(func=init_codex)

    init_claude_cmd = sub.add_parser(
        "init-claude", help="install project-local Claude Code hooks and MCP")
    init_claude_cmd.add_argument("--project", default=os.getcwd())
    init_claude_cmd.add_argument("--url", default=DEFAULT_URL)
    init_claude_cmd.add_argument("--dry-run", action="store_true")
    init_claude_cmd.add_argument("--replay-tools", action="store_true",
                                 help="also register the ToolAhead MCP tools "
                                      "for Read/Search replay hits")
    init_claude_cmd.add_argument("--strict", action="store_true",
                                 help="hide native file-tool analogs "
                                      "(implies --replay-tools)")
    init_claude_cmd.set_defaults(func=init_claude)

    init_ag_cmd = sub.add_parser(
        "init-antigravity",
        help="install workspace-local hooks (and optional MCP tools) for "
             "Google Antigravity")
    init_ag_cmd.add_argument("--project", default=os.getcwd())
    init_ag_cmd.add_argument("--url", default=DEFAULT_URL)
    init_ag_cmd.add_argument("--dry-run", action="store_true")
    init_ag_cmd.add_argument("--replay-tools", action="store_true",
                             help="also register the ToolAhead MCP tools for "
                                  "Read/Search replay hits")
    init_ag_cmd.set_defaults(func=init_antigravity)

    init_all_cmd = sub.add_parser(
        "init", help="install ToolAhead hooks (default) and optional MCP "
                     "tools for your agents")
    init_all_cmd.add_argument("--project", default=os.getcwd())
    init_all_cmd.add_argument("--url", default=DEFAULT_URL)
    init_all_cmd.add_argument(
        "--agent", choices=("both", "all", "codex", "claude", "antigravity"),
        default="both")
    init_all_cmd.add_argument("--dry-run", action="store_true")
    init_all_cmd.add_argument("--replay-tools", action="store_true",
                              help="also register the ToolAhead MCP tools "
                                   "for Read/Search replay hits")
    init_all_cmd.add_argument("--strict", action="store_true",
                              help="install coherent ToolAhead file-tool "
                                   "routing (implies --replay-tools)")
    init_all_cmd.set_defaults(func=init_all)

    trust_cmd = sub.add_parser(
        "trust", help="approve this workspace's toolahead.toml for service "
                      "pre-warming (revoked automatically on any change)")
    trust_cmd.add_argument("--project", default=".")
    trust_cmd.set_defaults(func=trust)

    allow_cmd = sub.add_parser("allow", help="allow one exact replay command")
    allow_cmd.add_argument("command")
    allow_cmd.add_argument("--project", default=os.getcwd())
    allow_cmd.set_defaults(func=allow_command)

    status_cmd = sub.add_parser("status", help="show metrics and latency breakdown")
    status_cmd.add_argument("--url", default="http://127.0.0.1:4242")
    status_cmd.add_argument("--json", action="store_true")
    status_cmd.set_defaults(func=status)

    mcp_cmd = sub.add_parser("mcp", help="serve ToolAhead tools over stdio MCP")
    mcp_cmd.add_argument("--workspace", default=os.getcwd())
    mcp_cmd.add_argument("--url", default=DEFAULT_URL)
    mcp_cmd.add_argument("--lookup-wait", type=float, default=0.25)
    mcp_cmd.add_argument("--replay-wait", type=float, default=125.0)
    mcp_cmd.add_argument("--command-timeout", type=float, default=120.0)
    mcp_cmd.add_argument("--no-events", action="store_true")
    mcp_cmd.set_defaults(func=mcp_serve)

    doctor_cmd = sub.add_parser("doctor", help="check local Codex integration")
    doctor_cmd.add_argument("--project", default=os.getcwd())
    doctor_cmd.add_argument("--url", default="http://127.0.0.1:4242")
    doctor_cmd.set_defaults(func=doctor)

    codex_cmd = sub.add_parser("codex", help="run codex exec --json with reasoning relay")
    codex_cmd.add_argument("--event-url")
    codex_cmd.add_argument("--event-timeout", type=float, default=0.5)
    codex_cmd.add_argument("codex_args", nargs=argparse.REMAINDER)
    codex_cmd.set_defaults(func=codex_exec)
    return parser


GETTING_STARTED = """ToolAhead — your agent's next tool call, already done.

Get started in the project you want to accelerate:

  toolahead init            connect Claude Code and Codex (hooks only,
                            replaces none of their tools)
  toolahead allow "CMD"     let one exact test/lint command be reused
  toolahead serve           run the local daemon for this workspace

Then use your agent as usual. `toolahead status` shows what was saved.

Optional: declare dev servers in toolahead.toml and approve them once with
`toolahead trust` to have them pre-warmed while the model reasons.

Full list of commands: toolahead --help
Docs: https://github.com/michael-ra/toolahead
"""


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    if getattr(args, "func", None) is None:
        print(GETTING_STARTED, end="")
        return 0
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
