"""Command-line entry point for the ToolAhead prototype."""

from __future__ import annotations

import argparse
import json
import os
import shlex
import shutil
import subprocess
import sys
import urllib.request
from pathlib import Path

from .tool_contracts import replayable_command


ROOT = Path(__file__).resolve().parent
CODEX_HOOK = ROOT / "codex_hook.py"
CLAUDE_HOOK = ROOT / "prefetch_hook.py"
REPLAY_HELPER = ROOT / "prefetch_replay.py"
MCP_SERVER = ROOT / "mcp.py"
TOOL_CONTRACTS = ROOT / "tool_contracts.py"
STATS = ROOT / "prefetch_stats.py"
DEFAULT_URL = "http://127.0.0.1:4242"
MCP_BEGIN = "# >>> ToolAhead managed MCP >>>"
MCP_END = "# <<< ToolAhead managed MCP <<<"
MCP_TOOL_NAMES = [
    "read_file", "search", "list_files", "edit_file", "write_file", "run",
]
CLAUDE_NATIVE_ANALOGS = ["Read", "Grep", "Glob", "Edit", "Write"]


def _handler(command: str, *, timeout: int = 8) -> dict:
    return {"type": "command", "command": command, "timeout": timeout,
            "statusMessage": "ToolAhead"}


def _group(command: str, *, matcher: str | None = None,
           timeout: int = 8) -> dict:
    value = {"hooks": [_handler(command, timeout=timeout)]}
    if matcher is not None:
        value["matcher"] = matcher
    return value


def _merge_codex_hooks(config: dict, command: str) -> dict:
    hooks = config.setdefault("hooks", {})
    wanted = {
        "SessionStart": _group(command),
        "UserPromptSubmit": _group(command),
        "PreToolUse": _group(
            command, matcher="Bash|apply_patch"),
        "PostToolUse": _group(
            command, matcher="Bash|apply_patch"),
        "Stop": _group(command),
        # Codex clamps SessionEnd hooks to at most three seconds.
        "SessionEnd": _group(command, timeout=3),
    }
    for event, group in wanted.items():
        existing = hooks.setdefault(event, [])
        # Replace only groups previously generated by ToolAhead. This updates
        # copied hook paths without touching unrelated project hooks.
        existing[:] = [
            item for item in existing
            if not (isinstance(item, dict) and any(
                isinstance(hook, dict) and hook.get("statusMessage") == "ToolAhead"
                for hook in item.get("hooks", [])))
        ]
        existing.append(group)
    return config


def _runtime(project: Path) -> tuple[Path, Path]:
    runtime = project / ".toolahead" / "runtime"
    return runtime, runtime / "toolahead_mcp.py"


def _install_mcp_runtime(project: Path) -> Path:
    runtime, installed_mcp = _runtime(project)
    runtime.mkdir(parents=True, exist_ok=True)
    shutil.copy2(MCP_SERVER, installed_mcp)
    shutil.copy2(TOOL_CONTRACTS, runtime / "tool_contracts.py")
    return installed_mcp


def _codex_mcp_block(project: Path, installed_mcp: Path, url: str) -> str:
    values = {
        "command": "python3",
        "args": [str(installed_mcp), "--workspace", str(project),
                 "--url", url],
    }
    args = ", ".join(json.dumps(item) for item in values["args"])
    return "\n".join([
        MCP_BEGIN,
        "[mcp_servers.toolahead]",
        f"command = {json.dumps(values['command'])}",
        f"args = [{args}]",
        "startup_timeout_sec = 10.0",
        "tool_timeout_sec = 130.0",
        "enabled_tools = [" + ", ".join(json.dumps(name)
                                         for name in MCP_TOOL_NAMES) + "]",
        'env = { TOOLAHEAD_MCP_EVENTS = "1" }',
        MCP_END,
    ])


def _merge_managed_toml(existing: str, block: str) -> str:
    if MCP_BEGIN in existing or MCP_END in existing:
        if MCP_BEGIN not in existing or MCP_END not in existing:
            raise ValueError("incomplete ToolAhead managed block")
        start = existing.index(MCP_BEGIN)
        end = existing.index(MCP_END, start) + len(MCP_END)
        merged = existing[:start].rstrip() + "\n\n" + block + existing[end:]
    else:
        if "[mcp_servers.toolahead]" in existing:
            raise ValueError(
                "existing unmanaged [mcp_servers.toolahead] section; remove or rename it")
        merged = existing.rstrip() + ("\n\n" if existing.strip() else "") + block
    return merged.rstrip() + "\n"


def _merge_claude_hook(config: dict, command: str) -> dict:
    hooks = config.setdefault("hooks", {})
    existing = hooks.setdefault("PreToolUse", [])
    existing[:] = [
        item for item in existing
        if not (isinstance(item, dict) and any(
            isinstance(hook, dict) and hook.get("statusMessage") == "ToolAhead"
            for hook in item.get("hooks", [])))
    ]
    existing.append(_group(command, matcher="Bash", timeout=10))
    return config


def _enable_claude_strict_routing(config: dict) -> dict:
    """Hide native analogs so the model sees one coherent file-tool suite."""

    permissions = config.setdefault("permissions", {})
    if not isinstance(permissions, dict):
        raise ValueError("'permissions' must be an object")
    deny = permissions.setdefault("deny", [])
    if not isinstance(deny, list):
        raise ValueError("'permissions.deny' must be an array")
    for name in CLAUDE_NATIVE_ANALOGS:
        if name not in deny:
            deny.append(name)
    return config


def _strict_marker(project: Path) -> Path:
    return project / ".toolahead" / "strict-mcp"


def init_codex(args) -> int:
    project = Path(args.project).resolve()
    path = project / ".codex" / "hooks.json"
    mcp_config = project / ".codex" / "config.toml"
    hook_dir = project / ".codex" / "hooks" / "toolahead"
    installed_hook = hook_dir / "codex_hook.py"
    _runtime_dir, installed_mcp = _runtime(project)
    url = getattr(args, "url", DEFAULT_URL)
    command = shlex.join(["python3", str(installed_hook)])
    if path.exists():
        try:
            config = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            print(f"Cannot merge invalid {path}: {exc}", file=sys.stderr)
            return 2
        if not isinstance(config, dict):
            print(f"Cannot merge non-object {path}", file=sys.stderr)
            return 2
    else:
        config = {"description": "ToolAhead Codex lifecycle integration."}
    merged = _merge_codex_hooks(config, command)
    payload = json.dumps(merged, indent=2, ensure_ascii=False) + "\n"
    try:
        existing_toml = mcp_config.read_text(encoding="utf-8") \
            if mcp_config.exists() else ""
        mcp_payload = _merge_managed_toml(
            existing_toml, _codex_mcp_block(project, installed_mcp, url))
    except (OSError, ValueError) as exc:
        print(f"Cannot merge {mcp_config}: {exc}", file=sys.stderr)
        return 2
    if args.dry_run:
        print(f"# {path}\n{payload}# {mcp_config}\n{mcp_payload}", end="")
        return 0
    hook_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(CODEX_HOOK, installed_hook)
    shutil.copy2(REPLAY_HELPER, hook_dir / "prefetch_replay.py")
    _install_mcp_runtime(project)
    if getattr(args, "strict", False):
        marker = _strict_marker(project)
        marker.parent.mkdir(parents=True, exist_ok=True)
        marker.write_text("strict MCP routing enabled\n", encoding="utf-8")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(payload, encoding="utf-8")
    mcp_config.write_text(mcp_payload, encoding="utf-8")
    replay = project / ".prefetch-replay.json"
    if not replay.exists():
        replay.write_text('{\n  "commands": []\n}\n', encoding="utf-8")
    print(f"Installed Codex hooks: {path}")
    print(f"Installed Codex MCP:   {mcp_config}")
    print(f"Hook runtime:          {hook_dir}")
    print(f"MCP runtime:           {installed_mcp.parent}")
    print(f"Replay allowlist:       {replay}")
    if getattr(args, "strict", False):
        print("Routing:                strict (ToolAhead file tools preferred)")
    print("Open /hooks in Codex once to review and trust the hook definition.")
    return 0


def init_claude(args) -> int:
    project = Path(args.project).resolve()
    settings_path = project / ".claude" / "settings.json"
    mcp_path = project / ".mcp.json"
    runtime, installed_mcp = _runtime(project)
    installed_hook = runtime / "prefetch_hook.py"
    url = getattr(args, "url", DEFAULT_URL)
    hook_command = shlex.join(["python3", str(installed_hook)])

    def load_object(path: Path) -> dict:
        if not path.exists():
            return {}
        value = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(value, dict):
            raise ValueError("top-level JSON value must be an object")
        return value

    try:
        settings = _merge_claude_hook(load_object(settings_path), hook_command)
        if getattr(args, "strict", False):
            settings = _enable_claude_strict_routing(settings)
        mcp = load_object(mcp_path)
    except (OSError, ValueError) as exc:
        print(f"Cannot merge Claude project config: {exc}", file=sys.stderr)
        return 2
    servers = mcp.setdefault("mcpServers", {})
    if not isinstance(servers, dict):
        print(f"'mcpServers' must be an object in {mcp_path}", file=sys.stderr)
        return 2
    servers["toolahead"] = {
        "type": "stdio",
        "command": "python3",
        "args": [str(installed_mcp), "--workspace", str(project),
                 "--url", url],
        # The MCP server observes the actual tool completion, unlike the SSE
        # stream which only contains the model's requested tool call. Keep
        # lifecycle events enabled so successful Edit/Write calls can advance
        # latest-mutation-wins generations authoritatively.
        "env": {"TOOLAHEAD_MCP_EVENTS": "1"},
    }
    settings_payload = json.dumps(settings, indent=2, ensure_ascii=False) + "\n"
    mcp_payload = json.dumps(mcp, indent=2, ensure_ascii=False) + "\n"
    if args.dry_run:
        print(f"# {settings_path}\n{settings_payload}# {mcp_path}\n{mcp_payload}",
              end="")
        return 0
    _install_mcp_runtime(project)
    shutil.copy2(CLAUDE_HOOK, installed_hook)
    shutil.copy2(REPLAY_HELPER, runtime / "prefetch_replay.py")
    settings_path.parent.mkdir(parents=True, exist_ok=True)
    settings_path.write_text(settings_payload, encoding="utf-8")
    mcp_path.write_text(mcp_payload, encoding="utf-8")
    replay = project / ".prefetch-replay.json"
    if not replay.exists():
        replay.write_text('{\n  "commands": []\n}\n', encoding="utf-8")
    print(f"Installed Claude hooks: {settings_path}")
    print(f"Installed Claude MCP:   {mcp_path}")
    print(f"MCP runtime:            {installed_mcp.parent}")
    print(f"Replay allowlist:       {replay}")
    if getattr(args, "strict", False):
        print("Routing:                strict (native Read/Grep/Glob/Edit/Write hidden)")
    return 0


def init_all(args) -> int:
    agents = ("codex", "claude") if args.agent == "both" else (args.agent,)
    for agent in agents:
        result = init_codex(args) if agent == "codex" else init_claude(args)
        if result:
            return result
    return 0


def allow_command(args) -> int:
    if not replayable_command(args.command):
        print("Only a single deterministic test/build/lint command can be replayed; "
              "shell chains, substitutions, installers, and arbitrary commands are rejected.",
              file=sys.stderr)
        return 2
    project = Path(args.project).resolve()
    path = project / ".prefetch-replay.json"
    data = {"commands": []}
    if path.exists():
        try:
            loaded = json.loads(path.read_text(encoding="utf-8"))
            if isinstance(loaded, dict):
                data = loaded
        except (OSError, ValueError) as exc:
            print(f"Cannot update invalid {path}: {exc}", file=sys.stderr)
            return 2
    commands = data.setdefault("commands", [])
    if not isinstance(commands, list):
        print(f"'commands' must be a list in {path}", file=sys.stderr)
        return 2
    if args.command not in commands:
        commands.append(args.command)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n",
                    encoding="utf-8")
    print(f"Allowed exact replay command in {path}:\n  {args.command}")
    return 0


def serve(args) -> int:
    from . import proxy

    httpd, upstream_proxy, engine = proxy.build(
        port=args.port, upstream=args.upstream, workspace=args.workspace,
        table=args.table)
    port = httpd.server_address[1]
    print(f"ToolAhead listening on http://127.0.0.1:{port}")
    print(f"Workspace: {engine.workspace}")
    print(f"Anthropic upstream: {upstream_proxy.scheme}://"
          f"{upstream_proxy.host}:{upstream_proxy.port}")
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        return 0
    finally:
        engine.shutdown()
        httpd.server_close()
    return 0


def mcp_serve(args) -> int:
    from .mcp import ToolAheadMCP, serve_stdio

    server = ToolAheadMCP(
        args.workspace, args.url, lookup_wait=args.lookup_wait,
        replay_wait=args.replay_wait, command_timeout=args.command_timeout,
        report_events=not args.no_events)
    return serve_stdio(server)


def status(args) -> int:
    command = [sys.executable, str(STATS), "--url", args.url]
    if args.json:
        command.append("--json")
    return subprocess.call(command)


def codex_exec(args) -> int:
    from .codex_events import AsyncSender, DEFAULT_URL, relay

    codex_args = args.codex_args[1:] if args.codex_args[:1] == ["--"] else args.codex_args
    command = ["codex", "exec", "--json", *codex_args]
    sender = AsyncSender(args.event_url or DEFAULT_URL, args.event_timeout)
    try:
        process = subprocess.Popen(command, stdout=subprocess.PIPE, text=True,
                                   bufsize=1)
        assert process.stdout is not None
        relay(process.stdout, sender, sys.stdout)
        return int(process.wait())
    finally:
        sender.close()


def doctor(args) -> int:
    project = Path(args.project).resolve()
    checks = []
    checks.append(("Python >= 3.11", sys.version_info >= (3, 11), sys.version.split()[0]))
    codex = shutil.which("codex")
    checks.append(("Codex CLI", bool(codex), codex or "not found"))
    hooks = project / ".codex" / "hooks.json"
    checks.append(("Codex hooks", hooks.exists(), str(hooks)))
    codex_mcp = project / ".codex" / "config.toml"
    checks.append(("Codex MCP", codex_mcp.exists() and
                   "[mcp_servers.toolahead]" in codex_mcp.read_text(
                       encoding="utf-8", errors="replace"), str(codex_mcp)))
    claude_mcp = project / ".mcp.json"
    claude_ok = False
    try:
        claude_data = json.loads(claude_mcp.read_text(encoding="utf-8"))
        claude_ok = isinstance(claude_data.get("mcpServers", {}).get("toolahead"), dict)
    except (OSError, ValueError, AttributeError):
        pass
    checks.append(("Claude MCP", claude_ok, str(claude_mcp)))
    replay = project / ".prefetch-replay.json"
    checks.append(("Replay allowlist", replay.exists(), str(replay)))
    try:
        with urllib.request.urlopen(args.url.rstrip("/") + "/__prefetch/stats",
                                    timeout=1) as response:
            daemon = response.status == 200
    except Exception:
        daemon = False
    checks.append(("Local daemon", daemon, args.url))
    for label, ok, detail in checks:
        print(f"{'✓' if ok else '✗'} {label:18} {detail}")
    return 0 if all(ok for _label, ok, _detail in checks) else 1


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="toolahead")
    sub = parser.add_subparsers(dest="subcommand", required=True)

    serve_cmd = sub.add_parser("serve", help="start the local daemon/proxy")
    serve_cmd.add_argument("--workspace", default=os.getcwd())
    serve_cmd.add_argument("--port", type=int, default=4242)
    serve_cmd.add_argument("--upstream", default="https://api.anthropic.com")
    serve_cmd.add_argument("--table")
    serve_cmd.set_defaults(func=serve)

    init_cmd = sub.add_parser("init-codex", help="install project-local Codex hooks")
    init_cmd.add_argument("--project", default=os.getcwd())
    init_cmd.add_argument("--url", default=DEFAULT_URL)
    init_cmd.add_argument("--dry-run", action="store_true")
    init_cmd.add_argument("--strict", action="store_true",
                          help="route file tools through ToolAhead MCP")
    init_cmd.set_defaults(func=init_codex)

    init_claude_cmd = sub.add_parser(
        "init-claude", help="install project-local Claude Code hooks and MCP")
    init_claude_cmd.add_argument("--project", default=os.getcwd())
    init_claude_cmd.add_argument("--url", default=DEFAULT_URL)
    init_claude_cmd.add_argument("--dry-run", action="store_true")
    init_claude_cmd.add_argument("--strict", action="store_true",
                                 help="hide native file-tool analogs")
    init_claude_cmd.set_defaults(func=init_claude)

    init_all_cmd = sub.add_parser(
        "init", help="install ToolAhead MCP and hooks for one or both agents")
    init_all_cmd.add_argument("--project", default=os.getcwd())
    init_all_cmd.add_argument("--url", default=DEFAULT_URL)
    init_all_cmd.add_argument("--agent", choices=("both", "codex", "claude"),
                              default="both")
    init_all_cmd.add_argument("--dry-run", action="store_true")
    init_all_cmd.add_argument("--strict", action="store_true",
                              help="install coherent ToolAhead file-tool routing")
    init_all_cmd.set_defaults(func=init_all)

    allow_cmd = sub.add_parser("allow", help="allow one exact replay command")
    allow_cmd.add_argument("command")
    allow_cmd.add_argument("--project", default=os.getcwd())
    allow_cmd.set_defaults(func=allow_command)

    status_cmd = sub.add_parser("status", help="show metrics and latency breakdown")
    status_cmd.add_argument("--url", default="http://127.0.0.1:4242")
    status_cmd.add_argument("--json", action="store_true")
    status_cmd.set_defaults(func=status)

    mcp_cmd = sub.add_parser("mcp", help="serve ToolAhead tools over stdio MCP")
    mcp_cmd.add_argument("--workspace", default=os.getcwd())
    mcp_cmd.add_argument("--url", default=DEFAULT_URL)
    mcp_cmd.add_argument("--lookup-wait", type=float, default=0.25)
    mcp_cmd.add_argument("--replay-wait", type=float, default=125.0)
    mcp_cmd.add_argument("--command-timeout", type=float, default=120.0)
    mcp_cmd.add_argument("--no-events", action="store_true")
    mcp_cmd.set_defaults(func=mcp_serve)

    doctor_cmd = sub.add_parser("doctor", help="check local Codex integration")
    doctor_cmd.add_argument("--project", default=os.getcwd())
    doctor_cmd.add_argument("--url", default="http://127.0.0.1:4242")
    doctor_cmd.set_defaults(func=doctor)

    codex_cmd = sub.add_parser("codex", help="run codex exec --json with reasoning relay")
    codex_cmd.add_argument("--event-url")
    codex_cmd.add_argument("--event-timeout", type=float, default=0.5)
    codex_cmd.add_argument("codex_args", nargs=argparse.REMAINDER)
    codex_cmd.set_defaults(func=codex_exec)
    return parser


def main() -> int:
    args = build_parser().parse_args()
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
